export const music = [
	'9PM',
	'Stan',
	'Swan Lake',
	'Stereo hearts',
	'Cradles',
	'Night Changes',
	'Frozen',
	'Seven Nation Army',
	'Riverside',
	'Toxic',
];

export const images = [
	'./assets/arrowdown.png',
	'./assets/arrowup.png',
	'./assets/avatar.png',
	'./assets/bg.jpg',
	'./assets/book.png',
	'./assets/codewars.png',
	'./assets/email.png',
	'./assets/github.png',
	'./assets/location.png',
	'./assets/next.png',
	'./assets/pause.png',
	'./assets/phone.png',
	'./assets/portfolio.png',
	'./assets/prev.png',
	'./assets/project1.png',
	'./assets/project2.png',
	'./assets/project3.png',
	'./assets/project4.png',
	'./assets/project5.png',
	'./assets/resume.png',
	'./assets/resume.png',
	'./assets/script.png',
	'./assets/telegram.png',
	'./assets/vk.png',
	'./assets/web.png',
];
